eventFinderApp/urls.py
from django.urls import path
from . import views


app_name = 'eventFinderApp'

urlpatterns = [
    # event-finder/
    path('', views.IndexView.as_view(), name='index'),
    # event-finder/1
    path('<int:pk>/', views.EventView.as_view(), name='event'),
    # event-finder/my-account
    path('my-account/', views.AccountView.as_view(), name='account'),
    # event-finder/addevent
    path('addevent/', views.addevent, name='addevent'),
]

eventFinderProject/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from eventFinderApp import viewsets
from rest_framework.authtoken import views
from users import viewsets as UserViewsets




router = routers.DefaultRouter()
router.register(r'events', viewsets.EventViewSet)
router.register(r'users', UserViewsets.CustomUserViewSet)


urlpatterns = [
    path('event-finder/', include('eventFinderApp.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('api/', include(router.urls)),
    path(r'api-auth-token/', views.obtain_auth_token),

]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    # register
    path('register/', views.Register.as_view(), name='register'),
]

eventFinderApp/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()


class Event(models.Model):
    title = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    venue = models.CharField(max_length=200)
    start_date = models.DateField('start date')
    end_date = models.DateField('end date')
    start_time = models.TimeField('start time')
    end_time = models.TimeField('end time')
    categories = models.ManyToManyField('Category', related_name='events')
    host = models.ForeignKey(User, related_name='hosting_events', on_delete = models.CASCADE)
    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
  # add additional fields in here

  def __str__(self):
    return self.email

eventFinderApp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Event, Category

class DateInput(forms.DateInput):
   input_type = 'date'

class TimeInput(forms.TimeInput):
   input_type = 'time'


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = [
            'title', 
            'venue', 
            'location',
            'start_time',
            'end_time',
            'start_date',
            'end_date',
            'categories',
            ]
        widgets = {
           'start_time': TimeInput(), 
           'end_time': TimeInput(),
           'start_date': DateInput(), 
           'end_date': DateInput(),
       }

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

class CustomUserCreationForm(UserCreationForm):

  class Meta(UserCreationForm):
    model = CustomUser
    fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

  class Meta:
    model = CustomUser
    fields = ('username', 'email')

eventFinderApp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.shortcuts import render
from .models import Event
from .forms import EventForm


class IndexView(generic.ListView):
    template_name = 'eventFinderApp/index.html'
    context_object_name = 'events_list'

    def get_queryset(self):
        '''Return the events.'''
        return Event.objects.all()

class AccountView(generic.ListView):
    template_name = 'eventFinderApp/account.html'
    context_object_name = 'events_list'

    def get_queryset(self):
        '''Return the events.'''
        return Event.objects.filter(host = self.request.user)


class EventView(generic.DetailView):
    model = Event
    template_name = 'eventFinderApp/event.html'


def account(request):
    return render(request, 'eventFinderApp/account.html')


# the fucntional view for add event
def addevent(request):

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        eventform = EventForm(request.POST)
        # check whether it's valid:
        if eventform.is_valid():
            # save the data from the form
            event = eventform.save(commit=False) 
            event.host = request.user
            eventform.save()
            # redirect to the event list
            return HttpResponseRedirect(reverse('eventFinderApp:index'))
    # if a GET (or any other method) we'll create a blank form
    else:
        eventform = EventForm()
    # create the context for our template
    context = {'form': eventform}
    # build the response with our template
    template = 'eventFinderApp/addevent.html'
    return render(request, template, context)


# the Class based view for add event
class AddEventView(generic.View):

    # in the class basded view we handle the GET request with a get() function
    def get(self, request):
        # create our form instance
        eventform = EventForm()
        # assign it to the context
        context = {'form': eventform}
        # return our template with our context
        template = 'eventFinderApp/addevent.html'
        return render(request, template, context)

    # in the class based view we handle the POST request with a post() function
    def post(self, request):
        # we create our form instance with the data from the request
        eventform = EventForm(request.POST)
        # check if the form is valid
        if eventform.is_valid():
            # save the data of the form
            eventform.save()
            # redirect to the list of events 
            return HttpResponseRedirect(reverse('eventFinderApp:index'))
        # if the form isn't valid return the form (with automatic errors)
            # create the context for our template
        context = {'form': eventform}
        # build the response with our template
        template = 'eventFinderApp/addevent.html'
        return render(request, template, context)

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm

class Register(generic.CreateView):
  form_class = CustomUserCreationForm
  success_url = reverse_lazy('login')
  template_name = 'registration/register.html'
  
# Create your views here.

eventFinderApp/templates/eventFinderApp/account.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Account details:</h2>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <br>

    <h2>My events:</h2>
    {% if events_list %}
        {% for event in events_list %}
            {% include "./detailsBox.html" with event=event %}
        {% endfor %}
    
    {% else %}
    <p>You have not created any events.</p>
    <a href="{% url 'eventFinderApp:addevent' %}"> <button id="new-event">+ Add an new event</button></a>

    {% endif %}
</div>

{% endblock %}

eventFinderApp/templates/eventFinderApp/addevent.html
{% extends "base.html" %}
{% block content %}

{% load crispy_forms_tags %}

<div class="container">
<h3>Create an event</h3>

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
  <input type="submit" value="Create" id="submit">
</form>
</div>

{% endblock %}

eventFinderApp/templates/eventFinderApp/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Free Event Seeker</title>
        <meta name="description" content="">
        <meta name="author" content="Hayley van Waas">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Bungee+Shade&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}">
    </head>

    <body>
        <header>
            <div>
                <h1>Eventseeker</h1>
                <h2>The free event guide</h2>
            </div>
            {% include './nav.html' %}
        </header>

        {% block content %}{% endblock %}

    </body>

</html>

<footer>
        © Eventseeker 2019. All rights reserved
</footer>

eventFinderApp/templates/eventFinderApp/detailsBox.html
<div class="container">
<div class="details-box">
    <a href="{% url 'eventFinderApp:event' event.id %}">
        <h4>{{ event.title }}</h4>
        <br>
        <p>{{ event.name }}</p></li>
        <p>Location: {{ event.location }}</p>
        <p>Venue: {{ event.venue }}</p>
        <p>Date: {{ event.start_date }} - {{ event.end_date }}</p>
        <p>Time: {{ event.start_time }} - {{ event.end_time }}</p>

        <h3>This event was added by: {{ event.host.username }}</h3>

        
    </a>
</div>
</div>

eventFinderApp/templates/eventFinderApp/event.html
{% extends "base.html" %}

{% block content %}

<div class="container">

<h2>{{ event.title }}</h2>

<h3>This event was added by: {{ event.host.username }}</h3>


<ul>
    <li><p>Location: {{ event.location }}</p></li>
    <li><p>Venue: {{ event.venue }}</p></li>
    <li><p>Date: {{ event.start_date }} - {{ event.end_date }}</p></li>
    <li><p>Time: {{ event.start_time }} - {{ event.end_time }}</p></li>
    <li><p>Best suited for: {% for event in event.categories.all %}</p></li>
    <p>{{ event.name }}</p>
    {% endfor %}
</ul>

</div>


{% endblock %}

eventFinderApp/templates/eventFinderApp/index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h2 class="title">Upcoming events</h2>
    {% if events_list %}
        {% for event in events_list %}
            {% include "./detailsBox.html" with event=event %}
        {% endfor %}
</div>

<div class="container">        
    {% else %}
        <p>No current events are available.</p>
    {% endif %}
<br>
    {% if user.is_authenticated %}
    <h2 class="title">Can't find what you're looking for?</h2>
    <a href="{% url 'eventFinderApp:addevent' %}"> <button id="new-event">+ Add an new event</button></a>
    
    {% else %}
    <h2 class="title">Can't find what you're looking for?</h2><br>
    <p class="text-center">Please <a href="{% url 'login' %}"> login</a>  to add an event.</p>

    <p class="text-center">Don't have an account? Sign up now!</p>
    <a href="{% url 'users:register' %}"> <button id="new-event"> Sign up</button></a>
</div>
    
{% endif %}

{% endblock %}

templates/base.html
{% load staticfiles %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Free Event Seeker</title>
        <meta name="description" content="">
        <meta name="author" content="Jessica Kavanagh">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Bungee+Shade&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>

    <body>
        <header>
            <div class="container">
                <h1>Eventseeker</h1>
                <h2>The free event guide</h2>
                <br>
                {% if user.is_authenticated %}
                <h5>Hello {{ user.username }}!</h5>                
                {% else %}
                {% endif %}
            </div>
            {% include './nav.html' %}
        </header>

        {% block content %}{% endblock %}

    </body>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<footer>
    © Eventseeker 2019. All rights reserved
</footer>

</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="navbar-brand" href="#">
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
             </button>
                                        


             <div class="navbar-collapse collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                    <a class="nav-link" href="{% url 'eventFinderApp:index' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'eventFinderApp:account' %}">My account</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}

    </ul>
</div>
</div>
</nav>